# Site settings
title: Qiusheng Wu
email: wqs@binghamton.edu
description: "Dr. Qiusheng Wu's Research Site"


# Team names, titles and social links
people:
- name: Qiusheng Wu, PhD
  pic: me
  position: Assistant Professor
  social:
    - title: twitter
      url: http://twitter.com/giswqs
    - title: linkedin
      url: https://www.linkedin.com/in/qiushengwu
    - title: github
      url: http://github.com/giswqs


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/giswqs
  - title: linkedin
    url: https://www.linkedin.com/in/qiushengwu
  - title: github
    url: http://github.com/giswqs

# Postal address (add as many lines as necessary)
address:
  - line: Binghamton University
  - line: 4400 Vestal Parkway East
  - line: Binghamton, NY 13902

# Build settings
markdown: kramdown
permalink: pretty
