# Site settings
title: Qiusheng Wu
email: qwu18@utk.edu
description: "Dr. Qiusheng Wu's Academic Website"


# Team names, titles and social links
people:
- name: Qiusheng Wu, PhD
  pic: me
  position: Assistant Professor
  social:
    - title: twitter
      url: https://twitter.com/giswqs
    - title: wordpress
      url: https://lidarblog.com/
    - title: github
      url: https://github.com/giswqs
    - title: linkedin
      url: https://www.linkedin.com/in/qiushengwu
    - title: graduation-cap
      url: https://scholar.google.com/citations?user=vmml4_0AAAAJ&hl=en

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/giswqs
  - title: wordpress
    url: https://lidarblog.com/
  - title: github
    url: https://github.com/giswqs
  - title: linkedin
    url: https://www.linkedin.com/in/qiushengwu
  - title: graduation-cap
    url: https://scholar.google.com/citations?user=vmml4_0AAAAJ&hl=en

# Postal address (add as many lines as necessary)
address:
  - line: University of Tennessee
  - line: 1000 Phillip Fulmer Way
  - line: Knoxville, TN 37996

# Build settings
markdown: kramdown
permalink: pretty
